#
# li₃: the most RAD framework for PHP (http://li3.me)
#
# Copyright 2012, Union of RAD. All rights reserved. This source
# code is distributed under the terms of the BSD 3-Clause License.
# The full license text can be found in the LICENSE.txt file.
#

sudo: false
language: php

services:
  - mongodb
  - memcache
  - couchdb
  - redis
addons:
  apt:
    sources:
      - mongodb-3.4-trusty
    packages:
      - mongodb-org-server

env:
  # Run one build with as many enabled and compatible extensions as possible.
  # Keep in-sync with potential partial excludes in the `matrix` section.
  - DB=sqlite PHP_EXT="opcache memcached redis apcu" TESTS=all
  # Test each remaining database in isolation.
  - DB=mysql TESTS=data
  - DB=pgsql TESTS=data
  - DB=couchdb TESTS=data
  - DB=mongodb PHP_EXT=mongodb TESTS=data

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  exclude:
  include:
    # Just one exemplaric job.
    - php: nightly
      env: PHP_EXT=memcached TESTS=all
  allow_failures:
    - php: nightly
      env: PHP_EXT=memcached TESTS=all
  # Mark build as failed as soon as one job failed.
  fast_finish: true

before_script:
  - cd ..
  - cp -r lithium/tests/ci/app .
  # Install libraries.
  - mv lithium app/libraries/
  - git clone --branch=1.1 --depth=1 --quiet git://github.com/UnionOfRAD/li3_fixtures.git app/libraries/li3_fixtures
  # Switch into the new app.
  - cd app
  # Install environment dependencies.
  - php libraries/lithium/tests/ci/depends.php
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database lithium_test; create database lithium_test_alternative;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database lithium_test;' -U postgres; psql -c 'create database lithium_test_alternative;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mongodb' ]; then mongod --version; fi"

script:
  # Run all tests.
  - sh -c "if [ '$TESTS' = 'all' ]; then libraries/lithium/console/li3 test libraries/lithium/tests/cases; fi"
  - sh -c "if [ '$TESTS' = 'all' ]; then libraries/lithium/console/li3 test libraries/lithium/tests/integration; fi"
  # Run just the database related tests.
  - sh -c "if [ '$TESTS' = 'data' ]; then libraries/lithium/console/li3 test libraries/lithium/tests/cases/data; fi"
  - sh -c "if [ '$TESTS' = 'data' ]; then libraries/lithium/console/li3 test libraries/lithium/tests/integration/data; fi"
  # Run just the storage related tests.
  - sh -c "if [ '$TESTS' = 'storage' ]; then libraries/lithium/console/li3 test libraries/lithium/tests/cases/storage; fi"
  - sh -c "if [ '$TESTS' = 'storage' ]; then libraries/lithium/console/li3 test libraries/lithium/tests/integration/storage; fi"

notifications:
  email: false

# Enable container based infra.
sudo: false
